export const uniqueIdentifierParams = [
  {
    id: 1,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 2,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 3,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 4,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 5,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 6,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 7,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 8,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 9,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 10,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 11,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 12,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 13,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 14,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 15,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 16,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 17,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 18,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 19,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
  {
    id: 20,
    name: "Parameter name",
    description: "Exampledata populated",
    isSelected: false,
  },
];
